backend:
  name: git-gateway
  branch: main

media_folder: "assets/images/uploads"
public_folder: "/assets/images/uploads"

collections:
  - name: "content"
    label: "Site Content"
    files:
      - file: "content.json"
        label: "Homepage Content"
        name: "homepage"
        format: "json"
        fields:
          - { label: "Site Title", name: "site_title", widget: "string" }

          - label: "Hero"
            name: "hero"
            widget: "object"
            fields:
              - { label: "Heading", name: "heading", widget: "string" }
              - { label: "Subheading", name: "subheading", widget: "text" }
              - { label: "CTA Text", name: "cta", widget: "string" }
              - { label: "Background Image", name: "bg", widget: "image" }

          - label: "About"
            name: "about"
            widget: "object"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Text (supports line breaks)", name: "text", widget: "text" }

          - label: "Services"
            name: "services"
            widget: "object"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - label: "Items"
                name: "items"
                widget: "list"
                summary: "{{fields.name}}"
                fields:
                  - { label: "Service Name", name: "name", widget: "string" }
                  - { label: "Description", name: "description", widget: "text" }

          - label: "Portfolio / Case Studies"
            name: "portfolio"
            widget: "object"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - label: "Items"
                name: "items"
                widget: "list"
                summary: "{{fields.name}}"
                fields:
                  - { label: "Name", name: "name", widget: "string" }
                  - { label: "Description", name: "description", widget: "text", required: false }
                  - { label: "Image", name: "image", widget: "image" }

          - label: "Testimonials"
            name: "testimonials"
            widget: "object"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - label: "Items"
                name: "items"
                widget: "list"
                summary: "{{fields.author}}"
                fields:
                  - { label: "Quote", name: "text", widget: "text" }
                  - { label: "Author", name: "author", widget: "string" }

          - label: "Pricing"
            name: "pricing"
            widget: "object"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - label: "Plans"
                name: "plans"
                widget: "list"
                summary: "{{fields.name}} — {{fields.price}}"
                fields:
                  - { label: "Plan Name", name: "name", widget: "string" }
                  - { label: "Price", name: "price", widget: "string" }

          - label: "Contact"
            name: "contact"
            widget: "object"
            fields:
              - { label: "Heading", name: "heading", widget: "string" }
              - { label: "Text", name: "text", widget: "text" }
              - { label: "Email", name: "email", widget: "string" }
              - { label: "Phone (country code + number, e.g. 919999999999)", name: "phone", widget: "string" }

          - { label: "Footer Text", name: "footer_text", widget: "string" }
